spring.clickhouse.datasource.url=jdbc:clickhouse://localhost:8123/testing
spring.clickhouse.datasource.username=default
spring.clickhouse.datasource.password=
spring.clickhouse.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver